// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeyd9J6w5Vdbj4vUN6nt7OeEvLOhyJ5nE',
    appId: '1:537358017887:android:dab05495cd51713791c2ea',
    messagingSenderId: '537358017887',
    projectId: 'albion-stats-6a0e4',
    storageBucket: 'albion-stats-6a0e4.firebasestorage.app',
    databaseURL: 'https://albion-stats-6a0e4-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5lTvzOYqTooPQFFljS8mduRaBA3vbWFM',
    appId: '1:537358017887:web:b97bfd998f4d5f4c91c2ea',
    messagingSenderId: '537358017887',
    projectId: 'albion-stats-6a0e4',
    authDomain: 'albion-stats-6a0e4.firebaseapp.com',
    storageBucket: 'albion-stats-6a0e4.firebasestorage.app',
    measurementId: 'G-L0LCTJ48W4',
    databaseURL: 'https://albion-stats-6a0e4-default-rtdb.firebaseio.com',
  );
}
